### ISSUE TITLE
configuration.yaml example needed

### ISSUE THREAD

**Issue by zendick** [xannor/hass_gw1000#1]
Please include a sample code for configuration.yaml file.  

I can't figure out what is needed to get hass to detect the gw1000

**Comment by xannor** [comment]
I hadn't really expected anybody to pickup on this yet as I am still developing it.

the yaml its self is fairly simple, though I am contemplating learning the ins and outs of making it an integration and thus not need yaml.

Right now it only supports two platforms..

sensor:
- platform: gw1000

and

weather:
- platform: gw1000
  entity_id: #id of a configured weather entity, i.e. dark sky#

In theory you can specify the webhook to use via a webhook: attribute but I have not tested that, the default webhook name is gw1000.

to get the gw1000 to push you have to add #proto#://#servername#/api/webhook/#webhook# to the custom weather station in the livews app and tell it to use the ecowitt protocol not the weather underground one.

I only have the basic sensors implemented, station weather/wind/rain as the other sensors need to be dynamically created and I am still working on that.

the weather platform is just to provide a weather entity that uses the station data overlayed on top of another weather entities forecast and other data. This should work with any weather entity but I have only tested with dark sky.

Also the only sensor kit I have tested with is a ambient weather ws1900, I have the ecowitt rain/wind/temp sensors but have not set them up yet.

also, also: 
I'm in the US and for me the keys I get are imperial, again, I have only tested with that so if you are metric I do not know how well it will work.

**Comment by xannor** [comment]
I am closing this since I have not heard back of any more on this issue.
